### ISSUE TITLE
Prebuilt binaries are not compatible with the official step-ca Docker image

### ISSUE THREAD

**Issue by Avamander** [smallstep/step-kms-plugin#28]
It seems that the currently provided prebuilt binaries for step-kms-plugin are not compatible with the official step-ca Docker image. The container also lacks `go` that would allow manual compilation/install.

If possible, it would be nice if this plugin were included in the `step-ca` image or one of the prebuilt binaries of `step-kms-plugin` were compatible with it.

**Comment by maraino** [comment]
It probably makes sense to include it in HSM [Dockerfile](https://github.com/smallstep/certificates/blob/master/docker/Dockerfile.step-ca.hsm) as this plugin replaces the `step-*-init` commands.

**Comment by umegaya** [comment]
@maraino that's sounds great! it would be appreciate if images are prepared for glibc OS like centos or ubuntu, along with alpine. because proprietary hsm products' pkcs library and tools are tend to build for glibc and cannot recompile due to lack of source code.

**Comment by maraino** [comment]
@umegaya I guess it makes sense for the .hsm image of step-ca, at the moment you can download the release from https://github.com/smallstep/step-kms-plugin/releases in a layer and copy it to the final image.

**Comment by maraino** [comment]
Hi @umegaya closing this in favor of https://github.com/smallstep/certificates/issues/1286

**Comment by umegaya** [comment]
@maraino seems perfect! thank you for quick response 👍
