### ISSUE TITLE
Add docs on KMS URIs

### ISSUE THREAD

**Issue by maraino** [smallstep/step-kms-plugin#3]
### Description

We need to add docs on how to define URIs for all the KMSs. We can also add URI support on some of the KMSs that do not support it everywhere, e.g. cloudkms.

At some point we might want to support also [go-cloud](https://gocloud.dev) style URIs compatible with [cosign](https://github.com/sigstore/cosign/blob/main/KMS.md#basic-usage)

**Comment by tashian** [comment]
Do the docs in [Cryptographic Protection](https://smallstep.com/docs/step-ca/configuration/#cryptographic-protection) cover what you were expecting for this @maraino?

**Comment by tashian** [comment]
Looks like I added a link [in this readme commit](https://github.com/smallstep/step-kms-plugin/commit/f3ae330ab35c28875a45b28f519d061a7abe6690) when I deployed the new KMS docs.
