### ISSUE TITLE
When touich policy is enabled, user isn't prompted to touch the yubikey

### ISSUE THREAD

**Issue by tashian** [smallstep/step-kms-plugin#40]
When I run an ACME DA challenge on an attestation certificate with a touch policy that isn't "never", I need to touch the yubikey to complete the challenge. It would nice to prompt the user to touch the key in this scneario.

**Comment by maraino** [comment]
We don't have a way to know if you need to touch the key or not, in fact in device attestation you might need to touch it multiple times. What we can do is add a generic message.

**Comment by tashian** [comment]
Oh, that's annoying. But, I just noticed that Safari also doesn't prompt on this either when using the cert. So, I think the expectation is that you have to look for the light to flash on the key. Closing this for now.
